import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AuthContextProvider } from "@/context/AuthContext";
import { SubscribeContextProvider } from "@/context/SubscribeContext";
import Footer from "@/components/common/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
     <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f4f9f8]`}
        >
          <div className="">
            <AuthContextProvider>
              <SubscribeContextProvider>
                {children}
                <Toaster />
              </SubscribeContextProvider>
            </AuthContextProvider>
          </div>
          <Footer/>
        </body>
      </html>
  );
}
